### ISSUE TITLE
bf luis:cross-train not working as expected when using external file references which use intent filter

### ISSUE THREAD

**Issue by silverbulletgt** [microsoft/botframework-cli#1210]
## Versions
What CLI version are you using. - 4.12.0
What Nodejs version are you using - 12.13.0
What command-line interpreters are you using - Windows Command Prompt
What OS are you using - Windows 10

## Describe the bug
When using external references & filtering on a specific intent cross training includes all intents from the external file.
Using syntax for external reference intent filtering as described here: [External Reference Documentation](https://docs.microsoft.com/en-us/azure/bot-service/file-format/bot-builder-lu-file-format?view=azure-bot-service-4.0#external-references)

## To Reproduce
This repo contains the required files: [Repo with required files](https://github.com/silverbulletgt/bf-luis-cross-train-issue/tree/main/UsingExternalReferences)

Create a new folder with any name.
Create file: "External.lu" with text:
```
# ExternalIntentShouldBeIncluded
- Intent which should be included

# ExternalIntentShouldNotBeIncluded
- Intent which should NOT be included
```
Create file: "Application.lu" with text:
```
# InternalIntent
- Intent within application.lu

# ExternalIntentShouldBeIncluded
- [ExternalFile](External.lu#ExternalIntentShouldBeIncluded)
```
Create file: "Application.qna" with text (Note that insert code syntax here is the same as the syntax for the value in QnA Maker so this will look weird - Answer needs to be surrounded in ```):
```
# ? Question In ExternalFile.qna

```
Answer to question in ExternalFile.qna
```
```

Create file: "cross-train.config.json" with text
```
{
  "application": {
    "rootDialog": true
  }
}
```

In command prompt navigate to the folder you created & run the command:
`bf luis:cross-train -i . -o cross-train --config cross-train.config.json`

Navigate to the output folder "cross-train" & open the file "application.lu"
Body is:

```
> LUIS application information
> !# @app.versionId = 0.1
> !# @app.culture = en-us
> !# @app.luis_schema_version = 3.2.0


> # Intent definitions

# InternalIntent
- Intent within application.lu


# ExternalIntentShouldBeIncluded
- Intent which should be included


# ExternalIntentShouldNotBeIncluded
- Intent which should NOT be included


> # Entity definitions


> # PREBUILT Entity definitions


> # Phrase list definitions


> # List entities

> # RegEx entities




> Source: cross training. Please do not edit these directly!
# DeferToRecognizer_QnA_Application
- Question In ExternalFile.qna
```

## Expected behavior
The below intent: ExternalIntentShouldNotBeIncluded should not be included in the cross-trained application.lu file as it was not specified in the external file intent filter in the original application.lu file.
```
# ExternalIntentShouldNotBeIncluded
- Intent which should NOT be included
```

## Screenshots
![application lu cross-trained showing ExternalIntentShouldNotBeIncluded png](https://user-images.githubusercontent.com/76121744/115767872-94558380-a377-11eb-9e00-7860c084aed6.jpg)

## Additional context
I am working on creating a workflow which will allow the business team to manage the utterances for all of the intents throughout the organization in a single place.  They will do this through the LUIS portal in a single LUIS application.  Whenever there are updates the LUIS application will be exported to a .lu file & the corresponding .lu file will be updated in our code repository.

From there we will have a variety of LUIS "sub" applications which use the main .lu file but are only interested in some of the intents.  So, we will be using the external file intent filtering capability to achieve this.  Some of the LUIS "sub" applications also have related QnA Maker applications so we use bf:cross-train during our deployment process.  This is currently not working as expected & all intents & utterances from the main file are being included in the cross-trained .lu file.

[bug]

**Comment by silverbulletgt** [comment]
Possibly related to: [Issue 1205](https://github.com/microsoft/botframework-cli/issues/1205)

**Comment by silverbulletgt** [comment]
I found a workaround for this.  If I run 
`bf luis:convert -i application.lu -o application.json` -f
Then run 
`bf luis:convert -i application.json -o application.lu` -f

This converts the application.lu to json then back to an lu file.  This ends up eliminating the external references & placing the correct utterances from the external file into the application.lu file.  From there I can run the cross-train.

We have setup our Team City build process to do this action.

**Comment by boydc2014** [comment]
@cosmicshuai is this fixed in latest main?

**Comment by cosmicshuai** [comment]
@silverbulletgt You can try the latest dev version by run command `npm install -g @microsoft/botframework-cli@next`

I tried on the latest dev build. I run the command `bf luis:cross-train -i Application -o application/cross-trained-sub-folder --config application/cross-train.config.json --force` in your repo.
The result is 
application.lu
```

> LUIS application information
> !# @app.versionId = 0.1
> !# @app.culture = en-us
> !# @app.luis_schema_version = 3.2.0


> # Intent definitions

# LocalIntent
- utterance for LocalIntent


# ExternalIntent
- utterance for ExternalIntent


# DeferToRecognizer_QnA_application
- Question In Main application.qna
- Question In ExternalFile.qna


> # Entity definitions


> # PREBUILT Entity definitions


> # Phrase list definitions


> # List entities

> # RegEx entities



```

application.qna is
```
# ? Question In Main application.qna

**Filters:**
- dialogName=application
- dialogName=application

\```
Answer to question in application.qna
\```

> !# @qna.pair.source = crosstrained

# ? utterance for LocalIntent

**Filters:**
- dialogName=application
- dialogName=application

\```
intent=DeferToRecognizer_LUIS_application
\```

> Source: cross training. Please do not edit these directly!
> !# @qna.pair.source = crosstrained

# ? utterance for ExternalIntent
- Question In ExternalFile.qna

**Filters:**
- dialogName=application

\```
intent=DeferToRecognizer_LUIS_application
\```
```

**Comment by silverbulletgt** [comment]
@cosmicshuai Thank you for taking a look at this.  I tried out updating my version using npm ... @next.  I am still getting the same issue.  Please note that I have used the repo for another issue so there are a couple of applications within it.  The one which relates to this issue is in the folder: UsingExternalReferences.  The external.lu file which is contained in that folder includes 2 intents.  1 which is included in application.lu using the ../application.lu#intent syntax.  It looks like you were running your command on the application.lu from the "Application" folder which is not setup in the same way (not using intent filtering) so would not demonstrate the issue.

Showing npm update
![Showing npm update to @next png](https://user-images.githubusercontent.com/76121744/116311081-cfd9be80-a778-11eb-8f69-33596aadd27c.jpg)

The output I get is still (notice intent ExternalIntentShouldNotBeIncluded is included when it should not be):
application.lu

```
> LUIS application information
> !# @app.versionId = 0.1
> !# @app.culture = en-us
> !# @app.luis_schema_version = 3.2.0


> # Intent definitions

# InternalIntent
- Intent within application.lu


# ExternalIntentShouldBeIncluded
- Intent which should be included


# ExternalIntentShouldNotBeIncluded
- Intent which should NOT be included


> # Entity definitions


> # PREBUILT Entity definitions


> # Phrase list definitions


> # List entities

> # RegEx entities




> Source: cross training. Please do not edit these directly!
# DeferToRecognizer_QnA_Application
- Question In ExternalFile.qna
```

application.qna

```
# ? Question In ExternalFile.qna

**Filters:**
- dialogName=Application

/```
Answer to question in ExternalFile.qna
/```

> Source: cross training. Please do not edit these directly!
> !# @qna.pair.source = crosstrained

# ? Intent within application.lu
- Intent which should be included
- Intent which should NOT be included

**Filters:**
- dialogName=Application

/```
intent=DeferToRecognizer_LUIS_Application
/```


```

**Comment by cosmicshuai** [comment]
I will look into the intent filtering issue.

**Comment by tdurnford** [comment]
@cosmicshuai any update on this?
