### ISSUE TITLE
bf qna:export generates invalid .qna file

### ISSUE THREAD

**Issue by tsuwandy** [microsoft/botframework-cli#1294]
https://stackoverflow.com/questions/68576131/bf-cli-parsing-error-on-exported-qna-maker-knowledge-base

**Comment by munozemilio** [comment]
Fixed by #1308

**Comment by aarohi-001** [comment]
@munozemilio I am still facing the same issue while parsing the QnA file using this command:

`bf orchestrator:create --hierarchical --in ./CognitiveModels --out ./generated --model ./model`

Can you help out here
